### ISSUE TITLE
Pros and cons vs dockercloud/haproxy

### ISSUE THREAD

**Issue by modius** [madwire/dockercloud-nginx-proxy#5]
This looks like a great project.  Do you have a succinct list of pros and cons vs docker clouds standard recommendation of dockercloud/haproxy?

**Comment by madwire** [comment]
@modius Sorry for the late reply (was on holiday), I haven't really used the docker clouds haproxy as I wanted something more like heroku, in which I just setup new containers and they are auto discovered. It means I can run one instance of my LB image for all my apps.

**Comment by davidkassa** [comment]
Does this service require api roles/access to see the variables of the other services?

**Comment by madwire** [comment]
@modius Hope that answered your question. I'm ok to close this now?

**Comment by modius** [comment]
Thanks for getting back to me. 

PS. Worth noting that `dockercloud/haproxy` allows you to LB as many apps as you want from a single instance also
