### ISSUE TITLE
proxy fails when docker stacks are being used

### ISSUE THREAD

**Issue by maxfriedmann** [madwire/dockercloud-nginx-proxy#9]
In docker stacks you can name your services "web" or "database". The absolute service name will then be e.g. "my-cool-stack.web". If I deploy two of those, the service names are individual for docker itself, not for the dockercloud-nginx-proxy. I currently have a "web" for every stack I booted which leads to that just the first one works. 

Since it's just an internal marker, can we use service.uuid instead of service.name? (or maybe service.name + "-" + service.uuid?)

**Comment by madwire** [comment]
Are we talking about the upstream name in nginx? I have no issue with changing that. Can you have a go at a PR?

**Comment by madwire** [comment]
I guess changing this 

``` erb
upstream <%= service.name %> {
```

to this will do it.

``` erb
upstream <%= service.id %> {
```

service.id is a getter setup to look at uuid already, I just dont have the time today to test it.

**Comment by madwire** [comment]
@maxfriedmann If you can test the PR with your setup I would be happy to merge

**Comment by maxfriedmann** [comment]
no worries, I found a solution. thanks!

**Comment by jorgenfb** [comment]
Hi,
I had the same problem. I had multiple services with the same name, resulting in a config like this:
<details>
    upstream auth {                                                                                                                                                      
      server 10.7.0.13:80;                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                    

    server {                                                                                                                                                           
        server_name subdomain1.removed.com;                                                                                                                                   
        client_max_body_size 1m;                                                                                                                                         
        location / {                                                                                                                                                     
          proxy_pass http://auth;                                                                                                                                        
        }                                                                                                                                                                
      }                                                                                                                                                                  
                                                                                                                                                                          
    upstream auth {                                                                                                                                                      
      server 10.7.0.14:80;                                                                                                                                               
    }                                                                                                                                                                    
                                                                                                                                                                         
      server {                                                                                                                                                           
        server_name subdomain2.removed.com;                                                                                                                                   
        client_max_body_size 1m;                                                                                                                                         
        location / {                                                                                                                                                     
          proxy_pass http://auth;                                                                                                                                        
        }                                                                                                                                                                
      }     
</details>

I tested the branch/tag _proxy_to_service_id_ and it works like a charm :)

Looking forward to seeing it merged!

**Comment by madwire** [comment]
@jorgenfb Great, I will look at merging this today - after I have done one final round of testing
